"""
HTML Report Generator
Read the logs and charts generated by each detector, and generate a unified HTML report
"""
import os
from typing import List, Dict

try:
    from src.config_loader import get_config
except Exception:
    def get_config():
        class SimpleConfig:
            def get_output_dir(self):
                return "output"
            def get_logs_dir(self):
                return "output/logs"
            def get_plots_dir(self):
                return "plots"
        return SimpleConfig()


SECTION_MAP = [
    ("long_method_logs.txt", "Long Methods"),
    ("long_parameter_logs.txt", "Long Parameters"),
    ("too_many_branches_logs.txt", "Too Many Branches"),
    ("too_many_attributes_logs.txt", "Too Many Attributes"),
    ("too_many_methods_logs.txt", "Too Many Methods"),
    ("useless_exception_logs.txt", "Useless Exceptions"),
    ("commented_code_logs.txt", "Commented Code"),
    ("magic_number_logs.txt", "Magic Numbers"),
    ("unused_member_logs.txt", "Unused Members"),
    ("duplicate_code_logs.txt", "Duplicate Code"),
]


def _read_log_lines(log_path: str) -> List[str]:
    try:
        with open(log_path, encoding="utf8") as f:
            lines = [ln.strip() for ln in f.readlines() if ln.strip()]
        return lines
    except (OSError, IOError):
        return []


def _section_html(title: str, lines: List[str]) -> str:
    if not lines:
        return f"<section class='card'><h3>{title}</h3><p>No data available.</p></section>"
    items = "".join(f"<li><code>{line}</code></li>" for line in lines[:200])
    return f"<section class='card'><h3>{title}</h3><ul>{items}</ul></section>"


def _plots_html(plots_dir: str) -> str:
    if not os.path.isdir(plots_dir):
        return ""
    names = [n for n in sorted(os.listdir(plots_dir)) if n.lower().endswith((".png", ".jpg", ".jpeg", ".gif"))]
    if not names:
        return "<section class='card'><h3>Chart Previews</h3><p>No charts available.</p></section>"
    imgs = "".join(f"<div class='img-card'><img src='/plots/{name}' alt='{name}' /></div>" for name in names[:60])
    return f"<section class='card'><h3>Chart Previews</h3><div class='grid'>{imgs}</div></section>"


def generate_html_report(dirname: str) -> str:
    """
    Generate the HTML report file and return its path
    """
    cfg = get_config()
    output_dir = cfg.get_output_dir()
    logs_dir = cfg.get_logs_dir()
    plots_dir = cfg.get_plots_dir()

    os.makedirs(output_dir, exist_ok=True)

    sections = []
    for filename, title in SECTION_MAP:
        path = os.path.join(logs_dir, filename)
        lines = _read_log_lines(path)
        sections.append(_section_html(title, lines))

    plots_block = _plots_html(plots_dir)

    html = f"""
    <!doctype html>
    <html lang='zh'>
    <head>
        <meta charset='utf-8' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <title>Code Smell Report - {dirname}</title>
        <style>
            body {{font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif; margin:0; background:#f5f7fb;}}
            .wrap {{max-width: 1100px; margin: 32px auto;}}
            .panel {{background:#fff; border-radius:12px; box-shadow:0 6px 24px rgba(0,0,0,0.08); padding:18px;}}
            h1 {{margin:0 0 12px 0; font-size: 20px;}}
            .card {{background:#fff; border:1px solid #eee; border-radius:10px; padding:16px; margin: 16px 0;}}
            ul {{margin:0; padding-left:18px;}}
            code {{background:#eef3f9; padding:2px 4px; border-radius:4px;}}
            .grid {{display:grid; grid-template-columns: repeat(auto-fill, minmax(260px, 1fr)); gap:16px;}}
            .img-card {{background:#fff; border:1px solid #eee; border-radius:10px; padding:10px;}}
            .img-card img {{max-width: 100%; height:auto; display:block;}}
        </style>
    </head>
    <body>
        <div class='wrap'>
            <div class='panel'>
                <h1>Project: {dirname}</h1>
                <p>Below are the code smell logs summary and chart previews.</p>
            </div>
            {''.join(sections)}
            {plots_block}
        </div>
    </body>
    </html>
    """

    report_name = f"{dirname}_review.html"
    report_path = os.path.join(output_dir, report_name)
    with open(report_path, "w", encoding="utf8") as f:
        f.write(html)
    return report_path